Adding a --info flag to output meta information of the model
stan-dev/stanc3 pull request #810
Opened 2021-02-02 21:12 UTC by mandel

## Release notes

Proposal for issue #808.

Add an option `--info` which displays information about the Stan model. It currently generates a JSON object with a field `inputs`, `parameters`, `transformed parameters`, and `generated quantities` containing a dictionary where each entry corresponds to a variable in respectively the `data`, `parameters`, `transformed parameters`, and `generated quantities` blocks. To each variable is associated an object with two fields:
- `type`: the base type of the variable ("int" or "real").
- `dimensions`: the number of dimensions (0 for a scalar, 1 for a vector or row vector, etc.).

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

2021-02-03 23:28 UTC, seantalts requested changes
Code looks great, thanks! Would you mind adding a test to https://github.com/stan-dev/stanc3/tree/master/test/integration/cli-args for this? Thank you!

2021-02-04 20:56 UTC, mandel commented
Thanks, it helped me identify a bug!

2021-02-05 13:48 UTC, rok-cesnovar reviewed
A few suggestions to expand  the test with properly ignored output variables.

2021-02-05 13:48 UTC, rok-cesnovar commented on test/integration/cli-args/info.stan
> +  matrix[14, 14] t = p;
```suggestion
  matrix[14, 14] t = p;
  {
    real ignored_tp = r;
  }
```

2021-02-05 13:48 UTC, rok-cesnovar commented on test/integration/cli-args/info.stan
> +
```suggestion
model {
    real ignored_model = r;
```

2021-02-05 13:48 UTC, rok-cesnovar commented on test/integration/cli-args/info.stan
> +  real u = l[0];
```suggestion
  real u = l[0];
  {
    real ignored_gq = l[1];
  }
```

2021-02-05 15:14 UTC, mandel commented
Thank @rok-cesnovar you for your suggestions!

2021-02-07 23:21 UTC, seantalts commented
I made a couple minor edits in this PR (didn't have permission to just push them upstream to the info branch): https://github.com/deepppl/stanc3/pull/2

We're trying to use `Fmt` when possible, so switched to doing that, and also moved the `exit 0` and `ref` controlling info printing to `stanc.ml` since we're trying to move most of the I/O and interaction with the world into the driver when possible.

2021-02-08 16:10 UTC, seantalts approved these changes
Woo, thank you! This is great and should be really useful for anyone building stuff with or on top of Stan :D

2021-02-08 16:11 UTC, merged