Building ARM binaries in the pipeline
stan-dev/stanc3 pull request #832
Opened 2021-03-01 16:41 UTC by serban-nicusor-toptal

## Release notes

Added build stage for ARM in Jenkinsfile.

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

2021-03-01 16:45 UTC, rok-cesnovar requested changes
Looks great, maybe we rename this to linux-arm?

2021-03-01 16:45 UTC, rok-cesnovar commented on Jenkinsfile
> +                        sh "mv _build/default/src/stan2tfp/stan2tfp.exe bin/arm-stan2tfp"
```suggestion
                        sh "mkdir -p bin && mv `find _build -name stanc.exe` bin/linux-arm-stanc"
                        sh "mv _build/default/src/stan2tfp/stan2tfp.exe bin/linux-arm-stan2tfp"
```

2021-03-01 16:45 UTC, rok-cesnovar commented on Jenkinsfile
> +                        stash name:'arm-exe', includes:'bin/*'
```suggestion
                        stash name:'linux-arm-exe', includes:'bin/*'
```

2021-03-01 16:45 UTC, rok-cesnovar commented on Jenkinsfile
> +                unstash 'arm-exe'
```suggestion
                unstash 'linux-arm-exe'
```

2021-03-01 16:50 UTC, serban-nicusor-toptal commented
Thanks @rok-cesnovar ! I've renamed that locally but will wait before pushing to see if the pipeline is working as expected.
I have added a new `EC2 Fleet` for ARM with `0` instances so it will spin up only when we need it, this way we can now easily build ARM for other projects too.
I've seen that the [binaries workflow](https://github.com/stan-dev/stanc3/blob/master/.github/workflows/binaries.yml) is used so I will make that build ARM too if that's okay with you.

2021-03-01 16:58 UTC, rok-cesnovar commented
> I've seen that the binaries workflow is used so I will make that build ARM too if that's okay with you.

Definitely!

2021-03-01 18:59 UTC, serban-nicusor-toptal commented
Argh looks like Github Actions [do not offer](https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#about-github-hosted-runners) ARM based VMs as a service, only if we self-host an ARM based VM and use it for builds.
I can make the Jenkins ARM instance to self-register to GitHub  ( to avoid having one 24/7 ) when it boots but this is only working if we start a Jenkins job first, if it's the other way around GitHub won't have a machine available. Now it's a matter of usability I guess, if we only need it for releases it's enough in Jenkins, if we want to have arm in gh actions then we should go for it. I'm up for any that fits us best.
What do you think @rok-cesnovar ?

2021-03-01 19:04 UTC, rok-cesnovar commented
Ah yes, they do not. 

In that case its just Jenkins for ARM on releases.The point of the GHA builder is that anyone can clone the repo and build the binaries for themselves so those cant rely on our instances/Jenkins.

2021-03-01 23:58 UTC, serban-nicusor-toptal commented
Hey Rok, any idea why it's failing [here](https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3/detail/PR-832/13/pipeline/) ?

2021-03-02 07:56 UTC, rok-cesnovar commented
This seems to be caused by slight numerical differences (maybe due to different CPU architecture). Just comment out `eval $(opam env) time dune runtest --profile static --verbose` as it isnt really needed for building binaries. We can make this data gen resistant to this numerical differences at a later point.

2021-03-02 12:26 UTC, rok-cesnovar approved these changes

2021-03-02 12:26 UTC, merged

2021-03-02 14:18 UTC, rok-cesnovar commented
Oh right, that would be better. So you now have to spawn the arm instance manually so it builds? Or it just takes awhile to spawn?

2021-03-02 14:20 UTC, serban-nicusor-toptal commented
It should spawn by itself when needed if everything works as expected.

2021-03-02 14:22 UTC, rok-cesnovar commented
Cool, then lets apply the fix you suggest.

2021-03-02 14:23 UTC, serban-nicusor-toptal commented
For some reason it's taking way longer than expected:
![image](https://user-images.githubusercontent.com/48496524/109662227-1ccf5900-7b6b-11eb-9381-86f6e0121b28.png)
I need to find a fix for this later, looks like it doesn't like our region :(